struct D2RuneInfo
{
  char const* code;
  char const* desc;
};
D2RuneInfo runes[] = {
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
  {"gcv", ""},
};